package aliyunQueryBillOverview

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"

	bssopenapi20171214 "github.com/alibabacloud-go/bssopenapi-20171214/v5/client"
	openapi "github.com/alibabacloud-go/darabonba-openapi/v2/client"
	util "github.com/alibabacloud-go/tea-utils/v2/service"
	"github.com/alibabacloud-go/tea/tea"
	_ "github.com/lib/pq"
)

var (
	resStr     string
	sqlConnStr string = fmt.Sprintf("postgres://%s:%s@%s:%s/%s?sslmode=disable",
		os.Getenv("POSTGRES_USER"),
		os.Getenv("POSTGRES_PASSWORD"),
		os.Getenv("POSTGRES_HOST"),
		os.Getenv("POSTGRES_PORT"),
		os.Getenv("POSTGRES_DB"))
)

type AutoGenerated struct {
	Item []struct {
		AdjustAmount          int     `json:"AdjustAmount"`
		BillAccountID         string  `json:"BillAccountID"`
		BillAccountName       string  `json:"BillAccountName"`
		BizType               string  `json:"BizType"`
		CashAmount            float64 `json:"CashAmount"`
		CommodityCode         string  `json:"CommodityCode"`
		Currency              string  `json:"Currency"`
		DeductedByCashCoupons int     `json:"DeductedByCashCoupons"`
		DeductedByCoupons     int     `json:"DeductedByCoupons"`
		DeductedByPrepaidCard int     `json:"DeductedByPrepaidCard"`
		InvoiceDiscount       float64 `json:"InvoiceDiscount"`
		Item                  string  `json:"Item"`
		OutstandingAmount     int     `json:"OutstandingAmount"`
		OwnerID               string  `json:"OwnerID"`
		PaymentAmount         float64 `json:"PaymentAmount"`
		PipCode               string  `json:"PipCode"`
		PretaxAmount          float64 `json:"PretaxAmount"`
		PretaxGrossAmount     float64 `json:"PretaxGrossAmount"`
		ProductCode           string  `json:"ProductCode"`
		ProductDetail         string  `json:"ProductDetail"`
		ProductName           string  `json:"ProductName"`
		ProductType           string  `json:"ProductType"`
		RoundDownDiscount     string  `json:"RoundDownDiscount"`
		SubscriptionType      string  `json:"SubscriptionType"`
	} `json:"Item"`
}

func ToSql() {
	data := []byte(Get())
	checkSqlTable(data)
	writeSql()

}

// Description:
//
// 使用AK&SK初始化账号Client
//
// @return Client
//
// @throws Exception
func CreateClient() (_result *bssopenapi20171214.Client, _err error) {
	// 工程代码泄露可能会导致 AccessKey 泄露，并威胁账号下所有资源的安全性。以下代码示例仅供参考。
	// 建议使用更安全的 STS 方式，更多鉴权访问方式请参见：https://help.aliyun.com/document_detail/378661.html。
	config := &openapi.Config{
		// 必填，请确保代码运行环境设置了环境变量 ALIBABA_CLOUD_ACCESS_KEY_ID。
		AccessKeyId: tea.String(os.Getenv("ALIBABA_CLOUD_ACCESS_KEY_ID")),
		// 必填，请确保代码运行环境设置了环境变量 ALIBABA_CLOUD_ACCESS_KEY_SECRET。
		AccessKeySecret: tea.String(os.Getenv("ALIBABA_CLOUD_ACCESS_KEY_SECRET")),
	}
	// Endpoint 请参考 https://api.aliyun.com/product/BssOpenApi
	config.Endpoint = tea.String("business.aliyuncs.com")
	_result = &bssopenapi20171214.Client{}
	_result, _err = bssopenapi20171214.NewClient(config)
	return _result, _err
}

func _main(args []*string) (_err error) {
	client, _err := CreateClient()
	if _err != nil {
		return _err
	}

	queryBillOverviewRequest := &bssopenapi20171214.QueryBillOverviewRequest{
		BillingCycle: tea.String("2024-07"),
	}
	runtime := &util.RuntimeOptions{}
	tryErr := func() (_e error) {
		defer func() {
			if r := tea.Recover(recover()); r != nil {
				_e = r
			}
		}()
		// 复制代码运行请自行打印 API 的返回值
		res, _err := client.QueryBillOverviewWithOptions(queryBillOverviewRequest, runtime)
		if _err != nil {
			return _err
		}
		resStr = res.Body.Data.Items.String()

		return nil
	}()

	if tryErr != nil {
		var error = &tea.SDKError{}
		if _t, ok := tryErr.(*tea.SDKError); ok {
			error = _t
		} else {
			error.Message = tea.String(tryErr.Error())
		}
		// 此处仅做打印展示，请谨慎对待异常处理，在工程项目中切勿直接忽略异常。
		// 错误 message
		fmt.Println(tea.StringValue(error.Message))
		// 诊断地址
		var data interface{}
		d := json.NewDecoder(strings.NewReader(tea.StringValue(error.Data)))
		d.Decode(&data)
		if m, ok := data.(map[string]interface{}); ok {
			recommend, _ := m["Recommend"]
			fmt.Println(recommend)
		}
		_, _err = util.AssertAsString(error.Message)
		if _err != nil {
			return _err
		}
	}
	return _err
}

func Get() string {
	err := _main(tea.StringSlice(os.Args[1:]))
	if err != nil {
		panic(err)
	}

	return resStr
}

func checkSqlTable(data []byte) {

	var p AutoGenerated
	err := json.Unmarshal(data, &p)
	if err != nil {
		log.Fatalln("解析返回值失败", err)
	}

	// 如果不存在表，则新建。
	var tableNameList []string
	for _, i := range p.Item {
		tableNameList = append(tableNameList, i.ProductCode)
	}

	uniqueList := removeDuplicates(tableNameList)

	db, err := sql.Open("postgres", sqlConnStr)
	if err != nil {
		log.Fatalln("连接数据库失败", err)
	}
	defer db.Close()

	rows, err := db.Query("SELECT * FROM pg_tables WHERE schemaname = 'public'")
	if err != nil {
		log.Fatalln("请求sql失败", err)
	}
	defer rows.Close()

	var sqlTableList []string
	for rows.Next() {
		var schemaname string
		var tablename string
		var tableowner string
		var tablespace *string
		var hasindexes string
		var hasrules string
		var hastriggers string
		var rowsecurity string

		err := rows.Scan(&schemaname, &tablename, &tableowner, &tablespace, &hasindexes, &hasrules, &hastriggers, &rowsecurity)
		if err != nil {
			log.Fatalln("获取sql结果失败", err)
		}
		sqlTableList = append(sqlTableList, tablename)
	}

	if err := rows.Err(); err != nil {
		log.Fatalln("查询sql失败", err)
	}

	creatTableName := difference(uniqueList, sqlTableList)
	log.Println("创建表：", creatTableName)
	if len(creatTableName) != 0 {
		for _, v := range creatTableName {
			sqlData := fmt.Sprintf(`
				CREATE TABLE "public"."%s" (
				BillingCycle VARCHAR(7) NOT NULL,
				DeductedByCoupons INTEGER NOT NULL,
				RoundDownDiscount INTEGER NOT NULL,
				ProductName VARCHAR(50) NOT NULL,
				ProductDetail VARCHAR(50) NOT NULL,
				ProductCode VARCHAR(50) NOT NULL,
				BillAccountID VARCHAR(50) NOT NULL,
				ProductType VARCHAR(50),
				DeductedByCashCoupons INTEGER NOT NULL,
				OutstandingAmount INTEGER NOT NULL,
				BizType VARCHAR(50),
				PaymentAmount INTEGER NOT NULL,
				PipCode VARCHAR(50),
				DeductedByPrepaidCard INTEGER NOT NULL,
				InvoiceDiscount INTEGER NOT NULL,
				Item VARCHAR(50),
				SubscriptionType VARCHAR(50),
				PretaxGrossAmount INTEGER NOT NULL,
				PretaxAmount INTEGER NOT NULL,
				OwnerID VARCHAR(50),
				Currency VARCHAR(50),
				CommodityCode VARCHAR(50),
				BillAccountName VARCHAR(50),
				AdjustAmount INTEGER NOT NULL,
				CashAmount INTEGER NOT NULL
				);`, v)
			rows2, err := db.Query(sqlData)
			if err != nil {
				log.Println(err)
			}
			if err := rows2.Err(); err != nil {
				log.Fatalln("创建表失败", err)
			}
		}
	}
}

func removeDuplicates(list []string) []string {
	unique := make(map[string]struct{})
	for _, item := range list {
		unique[item] = struct{}{}
	}
	result := make([]string, 0, len(unique))
	for item := range unique {
		result = append(result, item)
	}
	return result
}

func intersect(slice1, slice2 []string) []string {
	m := make(map[string]int)
	nn := make([]string, 0)
	for _, v := range slice1 {
		m[v]++
	}

	for _, v := range slice2 {
		times, _ := m[v]
		if times == 1 {
			nn = append(nn, v)
		}
	}
	return nn
}

func difference(slice1, slice2 []string) []string {
	m := make(map[string]int)
	nn := make([]string, 0)
	inter := intersect(slice1, slice2)
	for _, v := range inter {
		m[v]++
	}

	for _, value := range slice1 {
		times, _ := m[value]
		if times == 0 {
			nn = append(nn, value)
		}
	}
	return nn
}

func writeSql(data []byte) {
	var p AutoGenerated
	err := json.Unmarshal(data, &p)
	if err != nil {
		log.Fatalln("解析返回值失败", err)
	}

	for _, i := range p.Item {
		i.ProductCode
	}
}
